export const url = 'http://zero.webappsecurity.com/index.html'
export const url_feedback = 'http://zero.webappsecurity.com/feedback.html'
export const url_login = 'http://zero.webappsecurity.com/login.html'
export const login_username = 'username'
export const login_password = 'password'
